# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90f54672661335ddae0e9b0800733465deb94aa47219586327ff35c9b0e7bd1b52ab9c10307d76436171c0043fd82d5c36e96386eef8d6d80da077514f5b3880

test:
  secret_key_base: 87d0e64f7f7ecac4ccbbb15c3a81c59892f4f9b11040bd90b6dc0eaf9d8e920bcd11ef18dfb1e9d2bc2b18e5c1bbacd9e1225b070e6eb22c2eb35b8cf56d98ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
